{{- $gh  := "https://github.com/" -}}
{{- $amt := "/archive/master.tar.gz" -}}

[".local/share/sh"]
  type = "archive"
  url = "https://gist.github.com/jacksonp/9c2f547434b7d78d1b62/archive/master.tar.gz"
  stripComponents = 1

## ZSH

[".zaw"]
  type = "archive"
  url = "{{ $gh }}zsh-users/zaw{{ $amt }}"
  exact = true
  stripComponents = 1

[".local/share/zsh/completion.zsh"]
  type = "file"
  url = "https://raw.githubusercontent.com/twe4ked/dotfiles/master/shell/zsh/completion.zsh"

## oh-my-zsh

[".oh-my-zsh"]
  type = "archive"
  url = "{{ $gh }}ohmyzsh/ohmyzsh{{ $amt }}"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".local/share/oh-my-zsh-custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "{{ $gh }}zsh-users/zsh-syntax-highlighting{{ $amt }}"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".local/share/oh-my-zsh-custom/themes/powerlevel10k"]
    type = "archive"
    url = "{{ $gh }}romkatv/powerlevel10k/archive/v1.15.0.tar.gz"
    exact = true
    stripComponents = 1
